const {app,dialog}=require('electron')
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict')
const XLSX=require('xlsx')
const root=path.join(__dirname,'..'),profile=fs.mkdtempSync(path.join(root,'.cache/local-smoke-'))
app.setPath('userData',profile);app.disableHardwareAcceleration()
const emptyEdition=process.argv.includes('--empty')
if(emptyEdition)app.setPath('appData',profile)
const appRoot=emptyEdition?path.join(root,'desktop-empty-dist/win-unpacked/resources/app.asar'):process.argv.includes('--packaged')?path.join(root,'desktop-dist/win-unpacked/resources/app.asar'):root
const {openRegister}=require(path.join(appRoot,'desktop/database.cjs'))
const seed=openRegister(path.join(profile,'data/courtdesk.sqlite'));seed.close()
dialog.showSaveDialog=async(_,options)=>({canceled:false,filePath:path.join(profile,path.basename(options.defaultPath))})
dialog.showOpenDialog=async()=>({canceled:false,filePaths:[path.join(profile,fs.readdirSync(profile).find(n=>n.endsWith('.sqlite')))]})
dialog.showMessageBox=async()=>({response:1})
let main,networkRequests=0
app.on('browser-window-created',(_,win)=>{if(!main){main=win;win.show=()=>{};win.webContents.on('did-fail-load',(_,code,description)=>console.error('Load:',code,description))}})
require(path.join(appRoot,'desktop/main.cjs'))
if(emptyEdition)assert.equal(app.getPath('userData'),path.join(profile,'CourtDesk Import Test'))
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms))
async function until(check,label){for(let i=0;i<160;i++){if(await check())return;await wait(100)}throw new Error('Timed out: '+label)}
const js=source=>main.webContents.executeJavaScript(source)
const db=(op,payload)=>js(`window.desktop.database(${JSON.stringify(op)},${JSON.stringify(payload)??'undefined'})`).then(r=>{if(r.error)throw new Error(r.error);return r.value})
const click=text=>js(`[...document.querySelectorAll('button')].find(b=>b.textContent.trim()===${JSON.stringify(text)}).click()`)
const sample={RegdNo:921,CYear:'2016',Petitioner:'OFFLINE TEST ALICE',Respondets:'First respondent.,Second respondent',Type:'Writ Petition',Title:'WP',District:'Nagpur',Dated:'2026-09-26',Copies:'2'}
app.whenReady().then(async()=>{
 try {
  await until(()=>main&&!main.webContents.isLoading(),'startup')
  main.webContents.session.webRequest.onBeforeRequest({urls:['http://*/*','https://*/*','ws://*/*','wss://*/*']},(_,callback)=>{networkRequests++;callback({cancel:true})})
  await main.loadFile(path.join(appRoot,'build/index.html'))
  await until(()=>js(`document.body.textContent.includes('Local database')`),'local workspace')
  assert.equal((await db('info')).count,0)
  const alice=await db('create',sample)
  await db('create',{...sample,RegdNo:922,Petitioner:'OFFLINE TEST BOB'})
  await assert.rejects(()=>db('create',sample),/already exists/)
  await main.reload()
  await until(()=>js(`document.querySelectorAll('tbody tr').length===2`),'persistent local records')
  assert.equal(await js(`[...document.querySelectorAll('button')].find(b=>b.textContent.includes('New case')).disabled`),false)
  // Simulate a disconnected Windows machine; editing must stay enabled.
  await js(`Object.defineProperty(navigator,'onLine',{configurable:true,get:()=>false});window.dispatchEvent(new Event('offline'))`)
  await click('New case')
  await until(()=>js(`document.body.textContent.includes('New Case Entry')`),'new case form offline')
  const defaults=await js(`({date:document.querySelector('input[type=date]').value,year:document.querySelectorAll('.modal input[type=number]')[1].value,text:document.querySelector('.modal').textContent,titles:[...document.querySelector('select[aria-label="Title"]').options].map(o=>o.value)})`)
  const now=new Date();assert.equal(defaults.year,String(now.getFullYear()))
  assert.equal(defaults.date,`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`)
  assert.ok(!defaults.text.includes('Advocate address'));assert.ok(defaults.titles.includes('WP'))
  await click('Cancel')
  await js(`document.querySelector('button[title="Edit case"]').click()`)
  await until(()=>js(`document.body.textContent.includes('Save Changes')`),'edit form')
  await js(`(()=>{const input=[...document.querySelectorAll('.modal input')].find(i=>i.value==='OFFLINE TEST ALICE');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,'OFFLINE TEST ALICE UPDATED');input.dispatchEvent(new Event('input',{bubbles:true}))})()`)
  await js(`(()=>{const input=document.querySelector('input[aria-label="Respondent 1 number"]');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,'5');input.dispatchEvent(new Event('input',{bubbles:true}));const file=document.querySelector('input[type=file]'),dt=new DataTransfer();dt.items.add(new File(['%PDF-1.7 test attachment'],'case.pdf',{type:'application/pdf'}));file.files=dt.files;file.dispatchEvent(new Event('change',{bubbles:true}))})()`)
  await until(()=>js(`document.querySelector('.modal').textContent.includes('case.pdf')`),'PDF loaded')
  await click('Save Changes')
  await until(()=>js(`!document.querySelector('.modal')`),'save offline edit')
  assert.equal((await db('search',{query:'UPDATED'})).count,1)
  assert.equal((await db('pdf',{id:alice.id})).name,'case.pdf')
  assert.equal((await db('search',{query:'UPDATED'})).data[0].RespondentNumbers,'["5","2"]')
  await js(`(()=>{const input=document.querySelector('.search-input');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,'UPDATED');input.dispatchEvent(new Event('input',{bubbles:true}))})()`)
  await until(()=>js(`document.querySelectorAll('tbody tr').length===1`),'filtered results')
  await js(`(()=>{window.open=()=>({document:{write:html=>window.__printHTML=html,close:()=>{}}});document.querySelector('button[title="Print"]').click()})()`)
  const print=await js('window.__printHTML')
  assert.ok(print.includes('WP NO. ________/20'));assert.ok(print.includes('class="respondent-number">05</td>'));assert.ok(print.includes('OFFLINE TEST ALICE UPDATED'));assert.ok(print.includes('Regd. 921</strong>'));assert.ok(!print.includes('Regd. 921 /'))
  await js(`document.querySelector('.header-actions button').click()`)
  await until(()=>js(`!!document.querySelector('#export-scope')`),'export options');await js(`[...document.querySelectorAll('.modal-footer button')].find(b=>b.textContent.includes('Export records')).click()`)
  await until(()=>js(`!document.querySelector('#export-scope')`),'export completion')
  const workbook=XLSX.readFile(path.join(profile,fs.readdirSync(profile).find(n=>n.endsWith('.xlsx'))))
  assert.equal(XLSX.utils.sheet_to_json(workbook.Sheets.Cases).length,1)
  const imported=await db('import',[sample,{...sample,RegdNo:923,Petitioner:'IMPORTED OFFLINE'}]);assert.deepEqual(imported,{imported:1,skipped:1,remaining:0})
  await db('backup');await db('delete',{id:alice.id});assert.equal((await db('info')).count,2)
  await db('restore');assert.equal((await db('info')).count,3)
  await main.loadFile(path.join(appRoot,'build/index.html'))
  await until(()=>js(`document.querySelectorAll('tbody tr').length===3`),'restored records')
  await js(`document.querySelector('button[title="Delete case"]').click()`)
  await until(()=>js(`document.body.textContent.includes('Delete this case?')`),'delete confirmation')
  // Exercise the import dialog with a real CSV File, without network mocks.
  await click('Cancel');await click('Import')
  await until(()=>js(`!!document.querySelector('input[type=file]')`),'import dialog')
  const csvInput = 'Regd No,Year,Petitioner,Type,District,Date Filed\n924,2026,LOCAL CSV IMPORT,Civil,Nagpur,2026-09-26'
  await js(`(()=>{const input=document.querySelector('input[type=file]'),dt=new DataTransfer();dt.items.add(new File([${JSON.stringify(csvInput)}], 'sample.csv',{type:'text/csv'}));input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}))})()`)
  await until(()=>js(`document.body.textContent.includes('Check & preview')`),'mapping')
  await click('Check & preview')
  await until(()=>js(`document.body.textContent.includes('Import 1 new cases')`),'review')
  await click('Import 1 new cases')
  await until(()=>js(`document.body.textContent.includes('Import complete')`),'import complete')
  assert.equal((await db('info')).count,4)
  await click('Done')
  await js(`document.querySelector('button[title="Local database"]').click()`)
  await until(()=>js(`document.body.textContent.includes('Back up database')`),'database controls')
  assert.equal(networkRequests,0)
  await main.webContents.capturePage().then(image=>fs.writeFileSync(path.join(profile,'local-database.png'),image.toPNG()))
  console.log('PASS: disconnected startup, persistent SQLite CRUD, duplicate protection, UI editing, spreadsheet import, filtered Excel export, PDF content, backup/restore, zero network requests. Profile: '+profile)
  app.exit(0)
 }catch(error){console.error(error); if(main)console.error(await js(`document.body.textContent`).catch(()=>''));app.exit(1)}
})
