const test=require('node:test')
const assert=require('node:assert/strict')
const fs=require('node:fs'),path=require('node:path')
const {openRegister}=require('./database.cjs')
const root=path.join(__dirname,'../.cache/database-tests');fs.mkdirSync(root,{recursive:true})
const sample=(RegdNo, extra={})=>({RegdNo,CYear:'2026',Petitioner:'Alice',District:'Nagpur',Type:'Civil',Dated:'2026-09-26',...extra})
function fixture(t){const dir=fs.mkdtempSync(path.join(root,'run-'));const filename=path.join(dir,'test.sqlite');const db=openRegister(filename);t.after(()=>db.close());return {db,dir,filename}}
test('local writes persist and target one identity; duplicates are rejected',t=>{
 const {db,filename}=fixture(t)
 const a=db.create(sample(921)); db.create(sample(921,{CYear:'2025'}))
 assert.throws(()=>db.create(sample(921)),/UNIQUE/)
 db.update({id:a.id},sample(921,{Petitioner:'Updated'}))
 assert.equal(db.search({query:'Updated'}).count,1)
 db.delete({id:a.id});assert.equal(db.info().count,1)
 const second=openRegister(filename);assert.equal(second.search({},true).data[0].CYear,'2025');second.close()
})
test('filtering, literal characters, pagination and sorting work in SQL',t=>{
 const {db}=fixture(t)
 db.importRows([sample(82,{Petitioner:'Alice 100%_match'}),sample(821,{Dated:'2025-01-01',Adv:'COUNSEL'}),sample(9,{Petitioner:'Bob',Dated:null,District:'Other'})])
 assert.equal(db.search({query:'82',searchField:'RegdNo'}).count,2)
 assert.equal(db.search({query:'82',searchField:'RegdNo',matchMode:'exact'}).count,1)
 assert.equal(db.search({query:'%_'}).count,1)
 assert.equal(db.search({query:"' OR 1=1 --"}).count,0)
 assert.equal(db.search({advocate:'counsel',district:'Nagpur'}).count,1)
 assert.equal(db.search({dateFrom:'2026-01-01'}).count,1)
 const filters={sortField:'RegdNo',sortAsc:true,pageSize:1}
 assert.deepEqual([0,1,2].map(page=>db.search({...filters,page}).data[0].RegdNo),[9,82,821])
 assert.equal(db.search({sortField:'DROP TABLE cases'},true).count,3)
 assert.equal(db.search({},true).data.at(-1).Dated,null)
})
test('imports are atomic, skip existing identities and normalize empty years',t=>{
 const {db}=fixture(t)
 db.create(sample(1,{CYear:null}))
 assert.deepEqual(db.importRows([sample(1,{CYear:''}),sample(2)]),{imported:1,skipped:1,remaining:0})
 assert.throws(()=>db.importRows([sample(3),sample(4,{Petitioner:''})]),/Petitioner/)
 assert.equal(db.info().count,2)
 assert.throws(()=>db.create(sample(5,{Dated:'2026-02-30'})),/valid/)
})
test('backup and restore preserve records and keep a safety backup; invalid backup cannot erase data',t=>{
 const {db,dir}=fixture(t)
 db.create(sample(1));const backup=path.join(dir,'copy.sqlite');db.backup(backup)
 db.create(sample(2));const result=db.restore(backup)
 assert.equal(db.info().count,1)
 const safety=openRegister(result.safetyBackup);assert.equal(safety.info().count,2);safety.close()
 const invalid=path.join(dir,'invalid.sqlite');fs.writeFileSync(invalid,'not a database')
 assert.throws(()=>db.restore(invalid));assert.equal(db.info().count,1)
 assert.throws(()=>db.backup(db.info().path),/different/)
})

test('catalog includes supplied variants, excludes blank district, and persists new master entries',t=>{
 const {db,filename}=fixture(t)
 assert.equal(require('./catalog.json').districts.length,36)
 assert.ok(db.districts().some(r=>r.name==='Ahilyanagar'))
 assert.equal(db.types().filter(r=>r.short_type==='WP').length,2)
 assert.equal(db.types().filter(r=>r.short_type==='SMWP').length,3)
 assert.ok(!db.titles().includes('PIL'))
 db.addMaster({kind:'title',code:'NEW'})
 db.addMaster({kind:'type',code:'NEW',name:'New Category'})
 db.addMaster({kind:'advocate',name:'New Advocate'})
 const second=openRegister(filename)
 assert.ok(second.titles().includes('NEW'))
 assert.ok(second.types().some(r=>r.short_type==='NEW'&&r.long_type==='New Category'))
 assert.ok(second.advocates('new').some(r=>r.name==='New Advocate'))
 second.close()
})
test('one PDF per case replaces atomically and survives backups and changed case identity',t=>{
 const {db,dir}=fixture(t)
 const first=Buffer.from('%PDF-1.7 first'), replacement=Buffer.from('%PDF-1.7 replacement')
 const row=db.create(sample(100,{Title:'ACB',RespondentNumbers:'["2","5"]',PdfName:'first.pdf',PdfBytes:first}))
 assert.equal(Buffer.from(db.pdf(row).bytes).toString(),first.toString())
 db.update(row,{...row,RegdNo:101,PdfName:'replacement.pdf',PdfBytes:replacement})
 assert.equal(db.pdf(row).name,'replacement.pdf')
 assert.throws(()=>db.update(row,{...row,PdfName:'invalid.pdf',PdfBytes:Buffer.from('invalid')}),/valid PDF/)
 assert.equal(db.pdf(row).name,'replacement.pdf')
 assert.equal(db.search().data[0].RegdNo,101)
 const backup=path.join(dir,'pdf-backup.sqlite');db.backup(backup)
 db.restore(backup)
 const restored=db.search().data[0]
 assert.equal(restored.Title,'ACB');assert.equal(restored.RespondentNumbers,'["2","5"]')
 assert.equal(Buffer.from(db.pdf(restored).bytes).toString(),replacement.toString())
 db.delete(restored);assert.equal(db.info().count,0)
})
test('legacy version one databases migrate and restore without losing records',t=>{
 const {db,dir}=fixture(t)
 const {DatabaseSync}=require('node:sqlite')
 const legacy=path.join(dir,'legacy.sqlite'),old=new DatabaseSync(legacy)
 const legacyFields=require('./database.cjs').FIELDS.filter(f=>!['Title','RespondentNumbers','PdfName','CaseNumber','UpdatedAt'].includes(f))
 old.exec(`CREATE TABLE cases (id INTEGER PRIMARY KEY, ${legacyFields.map(f=>`"${f}" TEXT`).join(',')}); PRAGMA application_id=1128549204; PRAGMA user_version=1;`)
 old.prepare('INSERT INTO cases (RegdNo,CYear,Petitioner) VALUES (?,?,?)').run('77','2020','Legacy petitioner');old.close()
 db.restore(legacy);assert.equal(db.search().data[0].Petitioner,'Legacy petitioner')
 const migrated=openRegister(legacy);assert.equal(migrated.search().data[0].Title,null);migrated.close()
})

test('CaseNumber validates and UpdatedAt is auto-stamped on create and update',t=>{
 const {db}=fixture(t)
 assert.throws(()=>db.create(sample(500,{CaseNumber:'abc'})),/positive whole number/)
 const created=db.create(sample(500,{CaseNumber:'7373'}))
 assert.equal(created.CaseNumber,'7373')
 assert.ok(created.UpdatedAt,'UpdatedAt should be set on create')
 const createdStamp=created.UpdatedAt
 const updated=db.update({id:created.id ?? db.search({query:'Alice'}).data[0].id},{...created,Petitioner:'Alice updated'})
 assert.ok(updated.UpdatedAt && updated.UpdatedAt>=createdStamp,'UpdatedAt should refresh on update')
})
